mysql:
  image: hub.docker.vpclub.cn/vpclub/mysql:latest
  container_name: mysql
  net: host
  ports:
    - 3306:3306
  environment:
    MYSQL_ROOT_PASSWORD: "@vpclubdev"
  volumes:
    - ./mysqlConf:/etc/mysql/conf.d
    - /data/mysql:/var/lib/mysql
