redis-master:
  image: vpclub/redis:latest
  container_name: redis-master
  volumes:
    - ./data/redis/master:/data
  ports:
    - 6379:6379

redis-slave1:
  image: vpclub/redis:latest
  container_name: redis-slave1
  volumes:
    - ./redis-conf/6380:/usr/local/etc/redis/
    - ./data/redis/slave1:/data
  command: redis-server /usr/local/etc/redis/redis.conf --appendonly yes
  ports:
    - 6380:6379
  links:
    - redis-master
redis-slave2:
  image: vpclub/redis:latest
  container_name: redis-slave2
  volumes:
    - ./redis-conf/6381:/usr/local/etc/redis/
    - ./data/redis/slave2:/data
  command: redis-server /usr/local/etc/redis/redis.conf --appendonly yes
  ports:
    - 6381:6379
  links:
    - redis-master
redis-slave3:
  image: vpclub/redis:latest
  container_name: redis-slave3
  volumes:
    - ./redis-conf/6382:/usr/local/etc/redis/
    - ./data/redis/slave3:/data
  command: redis-server /usr/local/etc/redis/redis.conf --appendonly yes
  ports:
    - 6382:6379
  links:
    - redis-master


